fork = true
vsync = true

[font]
normal = ["Rec Mono Semicasual", "Adwaita Mono"]
size = 14

[font.features]
"Input Mono Narrow"   = [ "-liga", "-calt" ]
"Rec Mono Casual"     = [ "-liga", "-calt" ]
"Rec Mono Semicasual" = [ "-liga", "-calt" ]

[box-drawing]
mode = "native"

[box-drawing.sizes]
default = [2, 6]  # Thin and thick values respectively, for all sizes
