# see https://github.com/sigoden/aichat/blob/main/config.example.yaml
stream: true
wrap: 90
save: true
use_tools: 'fs'
model: novita:deepseek/deepseek-v3.2
compress_threshold: 40000
rag_embedding_model: google:gemini-embedding-001
rag_reranker_model: google:gemini-2.0-flash
clients:
  - type: openai-compatible
    name: novita
    api_base: https://api.novita.ai/openai
    models:
      - name: deepseek/deepseek-v3.2
      - name: zai-org/glm-5
  - type: openai-compatible
    name: google
    api_base: https://generativelanguage.googleapis.com/v1beta/openai/
    models:
      - name: gemini-embedding-001
        type: embedding
      - name: gemini-2.0-flash
        type: reranker
