[colors.primary]
background = "#e0e2ea"
foreground = "#14161b"

[colors.cursor]
cursor = "#000000"
text = "#ffffff"

[colors.normal]
black = "#07080d"
red = "#590008"
green = "#005523"
yellow = "#6b5300"
blue = "#004c73"
magenta = "#470045"
cyan = "#007373"
white = "#d7d8db"

[colors.bright]
black = "#4f5258"
red = "#590008"
green = "#005523"
yellow = "#6b5300"
blue = "#004c73"
magenta = "#470045"
cyan = "#007373"
white = "#eef1f8"
