[mgr]
ratio = [2,2,0]
sort_by = "natural"
show_hidden = true

[plugin]
preloaders = []
previewers = []

[[plugin.prepend_fetchers]]
id   = "git"
url  = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
url  = "*/"
run  = "git"
