[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[[mgr.prepend_keymap]]
on   = "<C-p>"
run  = "excluded toggle"
desc = "Toggle excluded files visibility"

[[mgr.prepend_keymap]]
on   = "<C-x>"
run  = "unyank"
desc = "Cancel yank status"
