[mgr]
border_style = { fg = "darkgray" }
border_symbol = ""
preview_hovered = { underline = false }
count_selected = { reversed = true, fg = "blue" }
count_copied = { reversed = true, fg = "yellow" }
count_cut = { reversed = true, fg = "red" }
marker_marked = { fg = "green", bg = "green" }
marker_selected = { fg = "blue", bg = "blue" }
marker_copied = { fg = "yellow", bg = "yellow" }
marker_cut = { fg = "red", bg = "red" }

[indicator]
padding = { open = "█", close = "█"}

[which]
cols = 2
mask = { bg = "grey" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
overall = { bg = "grey"}
progress_label = { bg = "grey", fg = "blue"  }
progress_error = { bg = "grey",  fg = "red" }
progress_normal = { bg = "grey",  fg = "blue" }

[mode]
normal_main = { bg = "grey", bold = true}
normal_alt = { bg = "grey", bold = true}
select_main = { fg = "red", bg = "grey", bold = true}
select_alt = { fg = "red", bg = "grey", bold = true}
unset_main = { fg = "blue", bg = "grey", bold = true}
unset_alt = { fg = "blue", bg = "grey", bold = true}

[tabs]
sep_outer = { open = "", close = "" }
sep_inner = { open = "", close = "" }
active = { fg = "cyan", bg = "grey", underline = true }
inactive = { fg = "white", bg = "reset"  }

[icon]
globs = []
dirs  = []
files = []
exts  = []
conds = []
