[mgr]
border_style = { fg = "darkgray" }
preview_hovered = { underline = false }
count_selected = { fg = "black", bg = "blue" }
count_copied = { fg = "black", bg = "yellow" }
count_cut = { fg = "black", bg = "red" }
marker_marked = { fg = "green", bg = "green" }
marker_selected = { fg = "blue", bg = "blue" }
marker_copied = { fg = "yellow", bg = "yellow" }
marker_cut = { fg = "red", bg = "red" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label = { bg = "black", fg = "black"  }
progress_normal = { bg = "black",  fg = "black" }

[mode]
normal_main = { bg = "grey", bold = true}
normal_alt = { bg = "grey", bold = true}
select_main = { fg = "red", bg = "grey", bold = true}
select_alt = { fg = "red", bg = "grey", bold = true}
unset_main = { fg = "blue", bg = "grey", bold = true}
unset_alt = { fg = "blue", bg = "grey", bold = true}

[tabs]
sep_outer = { open = "", close = "" }
sep_inner = { open = "", close = "" }
active = { fg = "cyan", bg = "grey", underline = true }
inactive = { fg = "white", bg = "reset"  }

[icon]
globs = []
dirs  = []
files = []
exts  = []
conds = []
