[mgr]
ratio = [2,2,0]
sort_by = "natural"
show_hidden = true

[files]
excludes = [
  { urn = "__pycache__", in = "*" },
  { urn = ".obsidian", in = "*" },
  { urn = ".git", in = "*" },
  { urn = "!.env", in = "*" },
]

[[plugin.prepend_fetchers]]
id   = "gitignore"
url  = "*"
run  = "gitignore"

[[plugin.prepend_fetchers]]
id   = "git"
url  = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
url  = "*/"
run  = "git"
