[colors.primary]
background = "#14161b"
foreground = "#e0e2ea"

[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[colors.normal]
black = "#07080d"
red = "#ffc0b9"
green = "#b3f6c0"
yellow = "#fce094"
blue = "#a6dbff"
magenta = "#ffcaff"
cyan = "#8cf8f7"
white = "#1b1e25"

[colors.bright]
black = "#79839c"
red = "#ffc0b9"
green = "#b3f6c0"
yellow = "#fce094"
blue = "#a6dbff"
magenta = "#ffcaff"
cyan = "#8cf8f7"
white = "#eef1f8"
